from django.db import models
# database related things will be done here 
# Create your models here.

class studens(models.Model):
    # id=models.AutoField()  this will be automatically be generated by django.
    name=models.CharField(max_length=100)
    age = models.IntegerField()
    email=models.EmailField()
    address=models.TextField(blank=True, null=True)



class car(models.Model):
    car_name=models.CharField(max_length=500)
    speed=models.IntegerField(default=50)
    
    def __str__(self) -> str:
        return self.car_name
    
